### ISSUE TITLE
Variable names with -# or _# cause errors 

### ISSUE THREAD

**Issue by wvankuipers** [SC5/sc5-styleguide#451]
Hello,

There seems to be a problem with variable names that have a hyphen or underscore followed by a number.

Example: 
    fontsize-1: 14px;

Generates the following error:

    Parsing error: Please check the validity of the block starting from line #1

    1*| $fontsize-1: 14px;

This seems to be incorrect, hyphens and underscores followed by a number are valid SASS variable names.

**Comment by jpbackman** [comment]
Hi @wvankuipers 

You're right, they should be allowed. This is an [open issue in gonzales-pe](https://github.com/tonyganch/gonzales-pe/issues/24) which we use to parse the style source and pick up the variable declarations and values, but it's been open for quite a while now.

As a workaround I can only suggest either removing the hyphen or underscore or adding something before the digit, e.g. `$fontsize-v1`. It might also be beneficial to think of renaming the variable to something more specific and descriptive such as `$fontsize-li` for clarity, readability and maintainability.

**Comment by wvankuipers** [comment]
@jpbackman Ok, should be fixed in gonzales-pe dev now. Guess it will be in stable soon.

**Comment by tdogg137** [comment]
I'm running into the same issue with variable name $color-gray-light-20 and I'm using gulp for sc5 styleguide.  Does anybody know if this is fixed?

**Comment by kvendrik** [comment]
+1 also having this issue

**Comment by techsoldaten** [comment]
+1 also having the issue

**Comment by hitautodestruct** [comment]
+1

**Comment by iegik** [comment]
+1

```
Generating style guide to output dir: styleguide
Parsing error: Please check validity of the block starting from line #55

53 |             $num: index($types, $type);
54 |             .-pd-#{nth($types_class, $num)}-#{$name} {
55*|                 padding-#{$type}: $padding;
56 |             }
57 |         }

Syntax: scss
Gonzales PE version: 3.0.0-31
```

**Comment by Darrenbydesign** [comment]
+1 
anyone know if this issue is fixed yet?

**Comment by wvankuipers** [comment]
Yes, this was fixed in [gonzales-pe v2.0.2](https://github.com/tonyganch/gonzales-pe/releases/tag/v2.0.2) and the styleguide generator is now on 3.0.0-31.

**Comment by kwiss** [comment]
Parsing error: Please check validity of the block starting from line #255
Syntax: less
Gonzales PE version: 3.0.0-31

@wvankuipers not really ?

**Comment by wvankuipers** [comment]
@kwiss It's fixed nu thuis commit I believe https://github.com/tonyganch/gonzales-pe/commit/c9f7f8d44722a105d0bda4088f60e2b63d12568e

What code are you rating to parse?

**Comment by jaynnasc** [comment]
I just installed the style guide and am still seeing this issue.  Here is my error:

`Parsing error: Please check validity of the block starting from line #7

5 |     @else
6 |         .no-padding-#{$side}
7*|             padding-#{$side}: 0 !important
9 | =vertical-align

Syntax: sass
Gonzales PE version: 3.0.0-31`

**Comment by wvankuipers** [comment]
Nope, you are missing a dot in line 7. It shoud read '.padding-#{$side}: 0 !important' 😉
