### ISSUE TITLE
Parsing error: Please check the validity of the block starting from line #515

### ISSUE THREAD

**Issue by SebastianoOlivo** [SC5/sc5-styleguide#508]
Hello, 

I'm triyng to use sc5-styleguide with grunt. When i launch grunt i get that message back :

``` 
Running "gulp:styleguide-generate" (gulp) task
Parsing error: Please check the validity of the block starting from line #515


Gonzales PE version: 3.0.0-12

Running "gulp:styleguide-applystyles" (gulp) task

Done, without errors.
MacBook-Pro-de-Sebastiano:eventLine sebastiano$ 
```

Here's my gruntfile

```


var gulp = require('gulp'),
styleguide = require('sc5-styleguide'),
source = 'css/*.scss',
outputPath = 'output';

module.exports = function(grunt) {

grunt.initConfig({
  pkg: grunt.file.readJSON('package.json'),
  gulp: {
    'styleguide-generate': function() {
      var outputPath = 'output';
      return gulp.src(source)
        .pipe(styleguide.generate({
            title: 'Event Line Style Guide',
            server: true,
            rootPath: outputPath
          }))
        .pipe(gulp.dest(outputPath));
    },
    'styleguide-applystyles': function() {
      gulp.src('source')
        .pipe(styleguide.applyStyles())
        .pipe(gulp.dest('output'));
    }
  },
  watch: {
    scss: {
      files: 'css/*.css',
      tasks: ['scss', 'gulp:styleguide-generate', 'gulp:styleguide-applystyles']
    }
  }
});

grunt.loadNpmTasks('grunt-gulp');

grunt.registerTask('default', ['gulp:styleguide-generate', 'gulp:styleguide-applystyles']);

};

```
I do not know where this error comes , not even the file I need to check the # 515 line

Thanks,

Sebastiano

**Comment by Jaswetz** [comment]
This seems like a similar bug as: https://github.com/SC5/sc5-styleguide/issues/4

**Comment by discipolo** [comment]
i believe you mean its similar to https://github.com/SC5/sc5-styleguide/issues/451

**Comment by Jaswetz** [comment]
Yep, thanks for the correction.

**Comment by DanielaValero** [comment]
I have got the same with variables:
```
Parsing error: Please check the validity of the block starting from line #71

69 |         .rhino-caption {
70 |             position: absolute;
71*|             background: @brand-color--darker;
72 |             display: none;
73 |             left: 0;

Gonzales PE version: 3.0.0-12

```

And with functions:

```
Parsing error: Please check the validity of the block starting from line #5

3 |  */
5*| @media all {
6 |     #ui .hotspotimage {
7 |         z-index:  ~`pageZIndex('hotspot-tooltip')`;

Gonzales PE version: 3.0.0-12

```

Are these issues being addressed with other tickets like: https://github.com/tonyganch/gonzales-pe/issues/59 ?

**Comment by hannu** [comment]
These problems are caused by gonzales-pe issues. As a workaround, you can ignore problematic styles:
```
// styleguide:ignore:start
Ignored styles
// styleguide:ignore:end
```
Alternatively, if files do not contain any KSS markup you can remove them from `styleguide.generate()` stream.
I know this is far from optimal solution but unfortunately we can not do much until this is fixed in gonzales-pe.

**Comment by DanielaValero** [comment]
Hi,

I noticed that my styleguide:generate doesnt run because:

* gonzales-pe depends on csscomb who has a bug with ~"" and ~`` (of LESS) and I use both of them. Added an ignore around the parts with ~ and it passed.
* There is a problem I don't understand (maybe the issue of the variables with hyphens), which causes gonzales-pe to break.

Conclusion, I can't add the ignore to the variables.... I will need to use something else while the dependt projects fix their issues. But I like this generator :+1:

**Comment by SebastianoOlivo** [comment]
In my case i didn't even use variables. I try with plain CSS but it still fail.

**Comment by hitautodestruct** [comment]
+1 Happens for me on random lines like `color: white` and `-webkit-transition: ...`

**Comment by nirmalkc** [comment]
Even I am stuck with the same issue. Gulp is throwing the same Gonzales PE version error for my '_mixins.scss' partial.

**Comment by ravaliya** [comment]
has there been any progress on this? i seem to be having issues with this:

[11:57:20] Starting 'html'...
[11:57:20] Starting 'scss'...
[11:57:20] Starting 'styleguide:generate'...
[11:57:20] Starting 'styleguide:applystyles'...
[11:57:20] Finished 'html' after 36 ms
Parsing error: Please check validity of the block starting from line #69

67 |
68 |     fw-widget-content > :not(.fw-dash-widget-flush) {
69*|         padding: $fw-dashboard-widget-content-margin;
70 |     }
71 | }

Syntax: scss
Gonzales PE version: 3.0.0-31
[11:57:21] Finished 'scss' after 856 ms
[11:57:21] Finished 'styleguide:applystyles' after 853 ms
[11:57:21] Finished 'styleguide:generate' after 860 ms
[11:57:21] Starting 'styleguide'...
[11:57:21] Finished 'styleguide' after 25 μs
[11:57:21] Starting 'dev'...

Developer mode!

SC5 Styleguide available at http://localhost:3000/

however, even removing or trying to ignore with comments doesn't seem to work. even though this looks like it works, nothing seems to load in the browser.
